language: python
python:
  - "3.5"
sudo: false

install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls

script:
  - coverage run --source cg setup.py test

after_success:
  coveralls

